# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3-4os8A-eAOXlNv4oY8uNg-0F2vdsRk
"""

! pip install requests python-docx

import requests
from docx import Document
import os
import json

subscription_key = "SUBSCRIPTION_KEY_HERE"
endpoint = 'https://api.cognitive.microsofttranslator.com'
location = 'LOCATION_REGION_HERE'
target_language = 'pt-br'
path = '/translate'

def translator_text(text, target_language):

  constructed_url = endpoint + path

  headers = {
      'Ocp-Apim-Subscription-Key': subscription_key,
      'Ocp-Apim-Subscription-Region': location,
      'Content-type': 'application/json',
      'X-ClientTraceId': str(os.urandom(16))
  }

  body = [{
      'text': text
  }]

  params = {
      'api-version': '3.0',
      'from': 'en',
      'to': target_language
  }

  request = requests.post(constructed_url, headers=headers, json=body, params=params)
  response = request.json()

  return response[0]["translations"][0]["text"]

translator_text("Hello there", target_language)

def translate_docx(input_file):
    doc = Document(input_file)
    full_text = []

    for paragraph in doc.paragraphs:
        translated_text = translator_text(paragraph.text, target_language)
        full_text.append(translated_text)

    translated_doc = Document()
    for line in translated_text:
        print(line)
        translated_doc.add_paragraph(line)
    path_translated_doc = input_file.replace(".docx", f"_{target_language}.docx")
    #translated_doc.add_paragraph('\n'.join(translated_text))
    translated_doc.save(path_translated_doc)


    return path_translated_doc

input_file = "/content/Better Together.docx"
translate_docx(input_file)
